import { Listing } from './types';

export const FEATURED_LISTINGS: Listing[] = [
  {
    id: 1,
    title: "Premium Self-Contain Unit",
    price: "₦350,000",
    priceValue: 350000,
    location: "Agbowo, UI",
    type: "Self-Contain",
    image: "https://picsum.photos/seed/apartment1/800/600",
    verified: true,
    noFee: true,
    beds: 1,
    baths: 1,
    area: "45 SQM",
    amenities: ["Water", "Security", "Prepaid Meter"],
    landmark: "5 mins from UI Gate",
    isRecentlyAdded: true,
    agent: { id: "agent_kunle", name: "Kunle Ajayi", rating: 4.8, isVerified: true },
    isFavorite: false
  },
  {
    id: 2,
    title: "Modern 1-Bedroom Flat",
    price: "₦550,000",
    priceValue: 550000,
    location: "Bodija",
    type: "1 Bedroom Flat",
    image: "https://picsum.photos/seed/apartment2/800/600",
    verified: true,
    noFee: false,
    beds: 1,
    baths: 1,
    area: "65 SQM",
    amenities: ["Solar", "Security", "Parking"],
    landmark: "Near Bodija Market",
    slotsLeft: 2,
    agent: { id: "agent_sarah", name: "Sarah Bolanle", rating: 4.5, isVerified: true },
    isFavorite: true
  },
  {
    id: 3,
    title: "Spacious Shared Apartment",
    price: "₦180,000",
    priceValue: 180000,
    location: "Akobo",
    type: "Shared",
    image: "https://picsum.photos/seed/apartment3/800/600",
    verified: true,
    noFee: true,
    beds: 2,
    baths: 2,
    area: "120 SQM",
    amenities: ["Water", "Security"],
    landmark: "Close to General Gas",
    isRecentlyAdded: true,
    agent: { id: "agent_mike", name: "Olawale Mike", rating: 4.2, isVerified: false },
    isFavorite: false
  },
  {
    id: 4,
    title: "Executive 1-Bedroom Apartment",
    price: "₦750,000",
    priceValue: 750000,
    location: "Jericho",
    type: "1 Bedroom Flat",
    image: "https://picsum.photos/seed/apartment4/800/600",
    verified: true,
    noFee: false,
    beds: 1,
    baths: 1,
    area: "80 SQM",
    amenities: ["Generator", "AC", "Security"],
    landmark: "Near Jericho Mall",
    isRecentlyAdded: false,
    agent: { id: "agent_bose", name: "Bose Adeniran", rating: 4.9, isVerified: true },
    isFavorite: false
  },
  {
    id: 5,
    title: "Cozy Student Self-Contain",
    price: "₦250,000",
    priceValue: 250000,
    location: "Samonda",
    type: "Self-Contain",
    image: "https://picsum.photos/seed/apartment5/800/600",
    verified: false,
    noFee: true,
    beds: 1,
    baths: 1,
    area: "40 SQM",
    amenities: ["Water", "Fenced"],
    landmark: "Walking distance to UI",
    isRecentlyAdded: true,
    agent: { id: "agent_ibrahim", name: "Ibrahim Lawal", rating: 3.8, isVerified: false },
    isFavorite: false
  },
  {
    id: 6,
    title: "Newly Built 1-Bedroom Flat",
    price: "₦600,000",
    priceValue: 600000,
    location: "Oluyole",
    type: "1 Bedroom Flat",
    image: "https://picsum.photos/seed/apartment6/800/600",
    verified: true,
    noFee: false,
    beds: 1,
    baths: 1,
    area: "70 SQM",
    amenities: ["Security", "Clean Water", "Parking"],
    landmark: "Behind Ring Road State Hospital",
    slotsLeft: 1,
    agent: { id: "agent_janet", name: "Janet Ade", rating: 4.7, isVerified: true },
    isFavorite: false
  },
  {
    id: 7,
    title: "Budget Shared Living",
    price: "₦120,000",
    priceValue: 120000,
    location: "Apata",
    type: "Shared",
    image: "https://picsum.photos/seed/apartment7/800/600",
    verified: false,
    noFee: true,
    beds: 3,
    baths: 2,
    area: "140 SQM",
    amenities: ["Water", "Spacious Kitchen"],
    landmark: "Near NNPC Depot",
    isRecentlyAdded: false,
    agent: { id: "agent_samuel", name: "Samuel Okon", rating: 4.0, isVerified: false },
    isFavorite: false
  },
  {
    id: 8,
    title: "Luxury Self-Contain Studio",
    price: "₦450,000",
    priceValue: 450000,
    location: "Ikolaba",
    type: "Self-Contain",
    image: "https://picsum.photos/seed/apartment8/800/600",
    verified: true,
    noFee: true,
    beds: 1,
    baths: 1,
    area: "50 SQM",
    amenities: ["AC", "Swimming Pool", "Gym"],
    landmark: "Behind Custom Office",
    isRecentlyAdded: true,
    agent: { id: "agent_kunle", name: "Kunle Ajayi", rating: 4.8, isVerified: true },
    isFavorite: true
  },
  {
    id: 9,
    title: "Comfortable 1-Bedroom Flat",
    price: "₦400,000",
    priceValue: 400000,
    location: "Ologuneru",
    type: "1 Bedroom Flat",
    image: "https://picsum.photos/seed/apartment9/800/600",
    verified: true,
    noFee: false,
    beds: 1,
    baths: 1,
    area: "60 SQM",
    amenities: ["Steady Water", "Secured Gate"],
    landmark: "Close to Eleyele",
    isRecentlyAdded: false,
    agent: { id: "agent_sarah", name: "Sarah Bolanle", rating: 4.5, isVerified: true },
    isFavorite: false
  },
  {
    id: 10,
    title: "Premium Hostel Room",
    price: "₦150,000",
    priceValue: 150000,
    location: "Under G, Lautech",
    type: "Self-Contain",
    image: "https://picsum.photos/seed/apartment10/800/600",
    verified: true,
    noFee: true,
    beds: 1,
    baths: 1,
    area: "30 SQM",
    amenities: ["Generator", "Water", "Security"],
    landmark: "2 mins from Under G Gate",
    isRecentlyAdded: true,
    slotsLeft: 3,
    agent: { id: "agent_tayo", name: "Tayo O.", rating: 4.6, isVerified: true },
    isFavorite: false
  },
  {
    id: 11,
    title: "Off-Campus 1-Bedroom",
    price: "₦280,000",
    priceValue: 280000,
    location: "Adenike, Ogbomoso",
    type: "1 Bedroom Flat",
    image: "https://picsum.photos/seed/apartment11/800/600",
    verified: false,
    noFee: false,
    beds: 1,
    baths: 1,
    area: "55 SQM",
    amenities: ["Well Water", "Fenced"],
    landmark: "Near Adenike Area",
    isRecentlyAdded: false,
    agent: { id: "agent_moses", name: "Moses Adewale", rating: 4.1, isVerified: false },
    isFavorite: false
  },
  {
    id: 12,
    title: "Standard Shared Room",
    price: "₦80,000",
    priceValue: 80000,
    location: "Stadium Area, Ogbomoso",
    type: "Shared",
    image: "https://picsum.photos/seed/apartment12/800/600",
    verified: true,
    noFee: true,
    beds: 2,
    baths: 1,
    area: "35 SQM",
    amenities: ["Reading Table", "Fan"],
    landmark: "Very close to Lautech Stadium",
    isRecentlyAdded: true,
    agent: { id: "agent_comfort", name: "Comfort I.", rating: 4.4, isVerified: true },
    isFavorite: false
  }
];
